version: '3.4'

services:
  acme.store.presentation:
    image: ${DOCKER_REGISTRY-}acmestorepresentation
    build:
      context: .
      dockerfile: ACME.Store.Presentation/Dockerfile
    ports:
    - "8080:80"
    depends_on:
    - database

  database:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "1q2w3e4r@#$"
      ACCEPT_EULA: "Y"